---
application:
  name: "posthog"
  project: "akenoX"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "psql"
  version: "12"
routers:
- name: "posthog-router"
  routes:
  - application_name: "posthog"
    paths:
    - "/"
